apiVersion: v1
kind: Pod
metadata:
  name: nodeport
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop

spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      name: nginx-port

---

apiVersion: v1
kind: Service
metadata:
  name: nodeport
  namespace: roboshop

spec:
  type: NodePort
  selector:
    environment: dev
    project: roboshop
  ports:
  - name: nodeport-ip
    protocol: tcp
    port: 80
    targetPort: nginx-port
  