apiVersion: v1
kind: Pod
metatdata:
  name: loadbalancer
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop

spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      name: nginx-server

---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  namespace: roboshop

spec:
  type: LoadBalancer
  selector:
    environment: dev
    project: roboshop
  ports:
  - name: nginx-port
    protocol: TCP
    port: 80
    targetPort: nginx-server