# apiVersion: v1
# kind: Pod
# metadata:
#   name: single-pod

# spec:
#   containers:
#   - name: nginx
#     image: nginx 
#     ports: 
#     - containerPort: 80

apiVersion: v1
kind: Pod
metadata: 
  name: pod
  namespace: roboshop

spec:
  containers:
  - name: nginx
    image: nginx
    Ports:
    - containerPort: 80
