apiVersion: v1
kind: Pod
metadata:
  name: label
  namespace: roboshop
  labels:
    tier: dev
    project: roboshop

spec: 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
