apiVersion: v1
kind: Pod
metadata:
  name: imagepull
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop

spec:
  containers:
  - name: imagepull
    image: nginx
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"