apiVersion: v1
kind: Pod
metadata:
  name: config-map-refer
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop
  
spec:
  containers:
  - name: config-map-refer
    image: nginx
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    env:
    - name: MONGO
      valueFrom:  
        configMapKeyRef:
          name: config-map
          key: MONGO

    - name: MONGO_URL
      valueFrom:
        configMapKeyRef:
          name: config-map
          key: MONGO_URL
